### ISSUE TITLE
Fast filtering does not work

### ISSUE THREAD

**Issue by timmib** [downthemall/downthemall#103]
### Your DownThemAll! and Browser Version and Language and Operating System
dta v 3.02, Firefox 45.3 esr, english, winxp se3

### Expected Behavior
Fast filtering used to choose the designated files.

### Actual Behavior
Has no effect for any of the dta v3 versions

### Steps To Reproduce
Try it on any site and any types of files

### Additional info such as log extracts
While the file filtering bugs are being worked out I would like to go back to version 2.0.18.  I can not find it.  Could someone point out a repository for the add on file?

TIA

Kim (a donor)

**Comment by nmaier** [comment]
Works for me, what filter are you using and can you provide a log?

**Comment by TheEnigmaBlade** [comment]
I seem to be having a similar problem. None of the example fast filters work, while I can select and modify normal filters without issue. I don't know how to retrieve logs for downthemall (debugging the addon to get an addon-scoped console didn't help).

The problem seems like it may be with how periods are handled in non-regex fast filters. While the filters `gif`, `http://imgur`, and `*.*` select something, the filters `.gif`, `imgur.com`, and `*.gif` do not. Regex filters work fine.

**Comment by nmaier** [comment]
Thanks @TheEnigmaBlade that clarifies things

**Comment by timmib** [comment]
sorry for not promptly replying.  I have attached a log
[logtokeep.zip](https://github.com/downthemall/downthemall/files/492487/logtokeep.zip).

simply, in the fast filtering something like *abc12* works whereas *abc12*.jpg will not.  My regex is rusty and can not seem to get the '.ext' to complete the filter.  But something like *abc12**jpg* does.  I am supporting EnigmaBlades comment, I believe.
TIA
Kim
