### ISSUE TITLE
(Firefox) Get '.txt' files on about:sync-log

### ISSUE THREAD

**Issue by scheinercc** [downthemall/downthemall#142]
**Is your feature request related to a problem? Please describe.**
I needed to download all `.txt` files on about:sync-log (visit with Firefox with enabled sync).
A message popup up that there were no links found.

**Describe the solution you'd like**
DTA would pick up the files.

**Describe alternatives you've considered**
Downloaded the files manually one-by-one ;)

**Additional context**
I assume this is either due to the way this FF specific page is built, or permissions. Just added as a feature request (low priority) in case this is actual possible.

**Comment by nmaier** [comment]
Those links are already local files on your system... about:sync-log just lists a directory on your local computer.

DownThemAll! filters out `file:` links because there usually is not point to essentially copy files. 

On top of that, WebExtensions are not allowed to access (most) `about:` pages, and "downloading" `file:` URLs is somewhat restricted too.

For those reasons, I will not change this behavior.

Thanks for taking the time to report this, either way.

**Comment by scheinercc** [comment]
> just lists a directory on your local computer.

🤦‍♂️

> WebExtensions are not allowed to access (most) about: pages

just what I suspected

> Thanks for taking the time to report this, either way.

Thank _you_ for talking the time for this detailed answer!
