### ISSUE TITLE
Permanent private browsing mode fails due to IDB not being available

### ISSUE THREAD

**Issue by Chumpyman** [downthemall/downthemall#159]
**Desktop (please complete the following information):**
 - OS: Windows 7, 64 bit
 - Browser Firefox Quantum 64-bit
 - Version 69.0.2

**Describe the bug**
Nothing Downloads at All

**To Reproduce**
1. Go to 'top right of browser'
2. Click on 'downthemall icon'
3. Scroll down to 'popup opens, there are files selected in the links section, but when download button is pushed nothing happens..'
4. See error "no error occurs. nothing happens at all"

**Expected behavior**
I expect a download to start

**Screenshots**

**Additional context**

**Comment by nmaier** [comment]
Does "nothing happens" mean really nothing, or does the selection window vanish and nothing happens afterwards?

Can you try the following:
- Open `about:debugging` in a tab
- Select This Firefox
- Navigate to the listing of DownThemAll!
- Click Inspect (or Debug depending on browser version)
- This will open a new "Inspector"/"Toolbox" tab. Keep it open and select the Console.
- Clear the console with that garbage can icon.
- Try to download again.
- Tell me about any new messages that appeared in that console. Vebatim text preferred (or screenshots)

**Comment by Chumpyman** [comment]
Mr. Maier,

Thanks for the response. You’re right the selection window vanishes and nothing happens afterwards. I’ve tried on a number of websites that I was able to download from in the past (before Firefox changed their protocols) and no luck.

I followed your instructions and attached is a screenshot from one download attempt. I hope its useful.

Regards,

C-Man

**Comment by nmaier** [comment]
You cannot attach screenshots by email. Please use the github site.

**Comment by Chumpyman** [comment]
I hope you can see the clip here.

![Clip](https://user-images.githubusercontent.com/56327416/66529507-bd822c00-ead1-11e9-94ab-118bed735379.jpg)

**Comment by nmaier** [comment]
It appears DownThemAll! cannot open the database for some reason where it stores download information. If there is no database there is no way to add downloads to it.

Now, I don't know why this happens. It might be your Firefox profile is broken, or some other software prevents Firefox from opening the database file on disk, or the disk housing the Firefox profile might be full or readonly. There can be plenty of reasons, and nothing I can determine from here.

You may try creating a new Firefox profile and see if that helps. There was one other person who reported a similar problem (tho another database file), and for them creating a new profile helped.

Here is some mozilla help article about managing firefox profiles: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles
You could just try a new profile without removing your main one, of course.

**Comment by Chumpyman** [comment]
Thank you. I’ll try a few things when I have time and let you know the outcome.

I am really hoping to get downthemall working again. It is so superior to any other downloader available. I know this from the years I used it in the days before quantum.

**Comment by Chumpyman** [comment]
Mr. Maier,
Everything seems to be working now. I turned off private browsing and upon restart I am able to download. I will let you know if I discover any other anomalies.

Thank you for your work in creating such a fine program and for your personal help. You will get a donation from me for sure.

![Clip_2](https://user-images.githubusercontent.com/56327416/66536463-085c6d80-eaeb-11e9-9add-7c9dda78ab71.jpg)

**Comment by nmaier** [comment]
Did you have permanent private browsing turned on?

**Comment by Chumpyman** [comment]
Yes, private browsing was turned on. When I switched it off downthemall started working, and I’ve kept private browsing off since then. All good, now.

**Comment by nmaier** [comment]
Thanks, that helps.

I totally forgot about permanent private browsing mode so far. In private windows, all database operations fail. This isn't usually a problem because DownThemAll! (the background page) does not run in a private browsing window itself. But when permanent private browsing is enabled even the DownThemAll! background page will be put into a private context, where the database (IndexDB) is not available.

This has to be detected somehow, and then DownThemAll! should use a mock memory-only Database instead. However just falling back to the memory-only database if IndexedDB reports an error is not great either, as there might be issues unrelated to private browsing that could cause this issue as well.

**Comment by 17500mph** [comment]
Has there been anything more on this? 
Resetting the profile is not always an optimal solution. 
Hmmm..   maybe a memory only database is the way to go all around. 
It's been quite a long time since I've had to play the FireFox Profile Game. So much so that I pretty much forgot about it until finding this thread..  ;-) 

'cause this is the End All to Get Them All.. and it's back. * .. if it can manage a list of queued files.

**Comment by darabana** [comment]
here to put some more wood on fire
DTA manager doesnt work if i have firefox.exe -private or "never remember history"   even though "allow in private.." is enabled on addon page

still usable though wo private; great addon ty

**Comment by nmaier** [comment]
It's tentatively working with permanent private browsing on, but I need to do more validation, in particular check with the TOR browser

**Comment by GodDrinkTeJAVA** [comment]
Hello, everyone who have been suffering this problem, I've found a workaround.

https://bugzilla.mozilla.org/show_bug.cgi?id=1639542

According to Bugzilla, setting dom.indexedDB.privateBrowsing.enabled to true at about:config can make IndexedDB work in private browsing. As this issue occurs because of Mozilla's policy not to use IndexedDB in PB, this means you can use DownloadThemAll with ease.

If you want perfectly intact PB, please be notified that IndexedDB does use file I/O to save values, which means turning this option on might lead to somewhat incomplete state private. I think this would be worthy tradeoff.

**Comment by nmaier** [comment]
The fixes (to be released with the next version) seem to work in the latest TOR browser as well. Closing this.
