### ISSUE TITLE
How to use Batch Descriptors whith several counting numbers

### ISSUE THREAD

**Issue by john-soda** [downthemall/downthemall#164]
**Is your feature request related to a problem? Please describe.**
I have URL's like 
`https://cdn.podigee.com/media/blubb-blubb_episode_7_bla-bla-bla_6_35.m4a`
`https://cdn.podigee.com/media/blubb-blubb_episode_8_bla-bla-bla_7_34.m4a`
`https://cdn.podigee.com/media/blubb-blubb_episode_9_bla-bla-bla_8_33.m4a`

I used this line to download the Files behind the URL's
`https://cdn.podigee.com/media/blubb-blubb_episode_[7:9]_bla-bla-bla_[6:8]_[35:33:-1].m4a`

but instead of three URL's I get 27 URL's.

**Describe the solution you'd like**
I'm looking for a way to use batch descriptors to generate only the three URL's I want.

**Describe alternatives you've considered**
I downloaded all 27 URL's and deleted the 24 small 4 byte files.
But it takes much longer than just downloading the three files.

**Additional context**

**Comment by john-soda** [comment]
Could you please add an example on your howto Page.

**Comment by nmaier** [comment]
This is not how batches work or are supposed to work or can work, really.

Consider e.g. `https://example.org/[1:10].[1:2].txt`... If it was to operate like you want, then what would be the result? `https://example.org/1.1.txt`, `https://example.org/2.2.txt`, `https://example.org/3.???????.txt`

Each batch descriptor is independent of any other batch descriptors. So in this example, the first one `1:10` expands the link to 10 links, and the second one expands all those links further for a total of `10 * 2 = 20` links.

What you want to do is have batch descriptors that are dependent on each other, which would also mean that each one has to generate the same number of replacements, or somehow specify what happens if there is an "overflow" (like should the `1:2` one start at 1 again, or should the remaining ones from `1:10` be ignored). This would create a very complex UI and/or syntax, and is therefore nothing I'd like to implement.

Also, there is no howto page (there are some old "manual" pages which are long outdated and therefore, while technically still public, not linked, I should probably completely disable them, tho)
