### ISSUE TITLE
DTA cease to exist, developer please respond 

### ISSUE THREAD

**Issue by oscalation** [downthemall/downthemall#232]
Hello

I need a few of the head developers to chime in here for a credible rebuttal to a corporate claim that DTA is going away. This claim was made because of the tone and rhetoric used in the following DTA blog post

http://www.downthemall.net/re-downthemall-and-webextensions-or-why-why-i-am-done-with-mozilla/ 

My company currently uses DTA to provide solutions to our customers in an automated fashion. We have had pushback from the executive team because of the prior blog post as it gives them fear that the DTA product will cease to exist and may not be a reliable solution. 

Any comments here would be great, and an updated blog post confirming the product is not going away would be even better. Please. I beg you. 

If anything, state in an updated blog post, if accurate, that the changes Mozilla is looking to make are not the solution the DTA team would take, but that if needed, you WOULD work around them and continue to offer DTA.

**Comment by poke** [comment]
It’s rather simple: Starting with the release of Firefox 57, legacy add-ons not built using WebExtensions will cease to work because Mozilla decided that. So far, they haven’t changed their decision.

For DTA, this means that the extension is effectively dead. Porting to WebExtensions would not only require *a lot of work* considering the size of the project but it also simply won’t work because WebExtensions do not give access to most of the APIs, DownThemAll would need to continue doing its job.

The list of [privileged APIs and their respective WebExtensions equivalent](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Comparison_with_XUL_XPCOM_extensions#Privileged_APIs) gives a pretty good idea about how it currently looks like: Most things simply don’t have a corresponding equivalent in WebExtensions, and it’s unlikely to get one in time for Firefox 57 (Nightly is currently on 56)—not to mention that Mozilla likely doesn’t even want to make all those APIs available for add-ons.

So if your company depends on DTA, I suggest you to switch that dependency out as quickly as you can. Unfortunately, I don’t have a good replacement either.

That’s my view on this topic, based on what I know what’s going on. I’m not that involves with the current Firefox developments, so I might be wrong about things here; but unless @nmaier disagrees, I’d just accept that as DTA’s fate.

**Comment by nmaier** [comment]
Yeah, what @poke said. It might be possible to continue DTA for the Firefox forks, e.g. Palemoon.
