### ISSUE TITLE
Where are the older versions?

### ISSUE THREAD

**Issue by noconflicts** [downthemall/downthemall#247]
The new version of Downloadthemall is confusing and doesn't allow me to pick a download location. The older version was so much more intuitive. It was just a click on the image and and then specify a destination. Please provide links to the previous versions.

**Comment by d7415** [comment]
Hi,

The older versions are available [here](https://github.com/downthemall/downthemall-legacy), but won't work with recent versions of Firefox because the APIs were removed.

It is possible to select a download location by entering it in the "subfolder" box. This has to be entered because of Web Extension limitations and must be relative to the Firefox downloads folder. It is possible to work around the second problem using [symbolic links](https://github.com/downthemall/downthemall/issues/2#issuecomment-557751776).

**Comment by nmaier** [comment]
I refer to @d7415's excellent answer
