### ISSUE TITLE
OneClick! Selector

### ISSUE THREAD

**Issue by jkhamlin** [downthemall/downthemall#28]
I turned on the OneClick! Selector feature to try it. I didn't like it, so I unchecked the box to turn it off, but find that it won't turn off. It is screwing up my browsing big time! Help!!!!

**Comment by nmaier** [comment]
The WebExtension does not have a OneClick Selector feature (yet)?
Are you talking about DownThemAll! 3 maybe?

**Comment by jkhamlin** [comment]
I'm talking about Downthemall Firefox extension.

**Comment by nmaier** [comment]
There is two. The old Firefox extension up to Version 3 which is hosted here:
https://github.com/downthemall/downthemall-legacy

And the new WebExtension, which is this one, and which does not have a "OneClick Selector"

**Comment by jkhamlin** [comment]
I'm on the old one. Should I just delete it and use the new one? Would that
solve my issue?

**Comment by nmaier** [comment]
Depends. The old one is a lot more powerful, but cannot work with new Firefox versions, that's why I made the new one. If you are a Firefox user, then please be advised that your Firefox itself has to be outdated a lot if you still can use the old DTA with it, meaning your Firefox has many unpatched security vulnerabilities. If you're using some alternative browser that still supports the original DownThemAll!, then I wouldn't recommend updating to the WebExtension at this point.

Either way, this is the wrong place to file an issue. https://github.com/downthemall/downthemall-legacy would be the appropriate place (for organizational reasons), although I do not have the time right now to look into issues regarding the old version.

The selector should turn off when you click the button again, btw. If it doesn't, then it might be broken in your browser. But the setting is not persisted, so just restarting the browser should turn it off either way.
