### ISSUE TITLE
Link to latest DTA WE 4.3 from Nov. 11, 2021

### ISSUE THREAD

**Issue by LeeBinder** [downthemall/downthemall#356]
Hello. On https://about.downthemall.org/changelog/ it states:

> 
> **Version 4.3 November 11, 2021**
>
> 	•	Fixed some issues where DownThemAll! would fail to work for users with permanent private browsing mode enabled as well as TorBrowser users.
> 	•	Hopefully fixed some issues where the translations would fail to load for some users.
> 	•	The Audio filter now applies to Links as well as Media.
> 	•	DownThemAll! will now use the title and description from metalink imports
> 	•	Context menu items in the selection and manager views can now be right-clicked
> 	•	Added some new translations: tr, fa, sv. And updated some other translations. Thanks to the people who contributed to these translations!
> 	•	Fixed an issue where the manager tab would load in the wrong window
> 	•	Fixed an issue where the selection window may not load.
> 	•	Chrome-based: Fixed an issue where the "overwrite" choice for file conflicts would not work.

but where can we download it?

Thank you for all your hard work on this neat extension!

**Comment by nmaier** [comment]
It's in the review queues of the different browsers add-on pages. Since I cannot know when exactly they will review it (and hopefully approve it too), I put the site online already. The alternative would be to not publish the changelog just yet, but also likely miss - maybe by a few hours - when the update gets approved and then have users ask where the changelog for 4.3 is.

mozilla and chrome talked about paraphrasing) "maybe it will take weeks because of corona", Microsoft still says "Expect to hear back from us in 7 business days."
So I honestly have no clue when it will become available in each browser.

**Comment by nmaier** [comment]
Seems Chrome managed to be first this time. the update there was just approved

**Comment by LeeBinder** [comment]
Hi Niels. Ah OK I understand - thanks for the background insights. Now your DTA WE is also online on its page on [Firefox Addons](https://addons.mozilla.org/en-US/firefox/addon/downthemall/versions/). Funny enough there it shows as 4.3.1 but with the exact same changes text as on [about.downthemall.org/changelog](https://about.downthemall.org/changelog/). Hmm. I wonder who determines version numbers?

BTW, in this context I've been scratching my head about a few things:

1. How come you're not simply adding the Extension packages for all browsers to [github.com/downthemall/downthemall/releases](https://github.com/downthemall/downthemall/releases)?
2. Are you aware that [github.com/downthemall/downthemall/releases](https://github.com/downthemall/downthemall/releases) and [code.downthemall.org/releases](https://code.downthemall.org/releases/) don't match?

**Comment by nmaier** [comment]
>Hi Niels.

*Nils ;)
Like [Nils Holgerson](https://en.wikipedia.org/wiki/The_Wonderful_Adventures_of_Nils), not Niels Bohr, according to my mom.

>Funny enough there it shows as 4.3.1 but with the exact same changes text as on about.downthemall.org/changelog. 

I do, the changelog only mentions 4.3 i.e. the major and minor version, as that's the "base" version number for which there are functional and bug fix changes to list.

The point release, i.e. the .1 in 4.3.1. is don't really mention. I use that for when a reviewer asks me to make small changes. 4.3.1 was the first such point release and it passed reviews on Firefox and Chrome on the first attempt, so there was no need for a 4.3.2.
But it may happen that I ship a 4.4.1 for firefox (because it passed) but Chrome demanded some minor changes and after that I release a 4.4.2 that is still supposed to be functionally equivalent to 4.4.1 on Firefox.  If I listed 4.4.2 instead of 4.4 as the latest version in the changelog then Firefox users would ask me "Where is it? Why am I only getting 4.4.1" even tho 4.4.1 is already the latest version for Firefox and equivalent to 4.4.2.
Hope that makes sense; it makes sense in my head at least.

>How come you're not simply adding the Extension packages for all browsers to github.com/downthemall/downthemall/releases?


There is not much of a point in doing so, as all the common browsers will require a valid signature by the browser maker (Mozilla, Chrome and other Chromium-based like Opera Microsoft Edge, Brave, Vivaldi) and some will outright refuse to install extensions from locations other than the official browser extensions sites.
Adding packages to the github releases page would only confuse most people because they cannot install from there anyway, as their browser won't let them.
The few people who could (e.g. Firefox Nightly users with signature checks disabled, or people using chrome in developer mode) I would expect could also just grab the extension from the browser extension website or do their own build.
The "confusion of the many" outranks the "convenience of the few" for me, that's why I don't provide the final packages on github or elsewhere right now.

**Comment by LeeBinder** [comment]
yes Nils (I DO want to address you correctly)

> Hope that makes sense

pretty much - thanks for taking the time explaining the background! Provided you're interested in a bit of constructive feedback about your approach, I'd suggest to follow through on it **_all_** the way, meaning to mention what you wrote on your official version changes page, in the current case like this:

### Minor version changes
**Version 4.3.1 November 21/22, 2021**
* small merely vendor-related adaptations for Mozilla Firefox and Google Chrome

### Major version changes
**Version 4.3 November 11, 2021**
.....

> "confusion of the many" outranks the "convenience of the few"

yep, now I see why I can only 100% agree. A libertarian tech geek like me tends to forget the general non-IT public. In that light and for congruence, if I may still two suggestions:

1. on [code.downthemall.org/releases](https://code.downthemall.org/releases/), replace 'also' with 'only' -> 
**Beware**: This archive **_only_** includes testing versions
2. match up [github.com/downthemall/downthemall/releases](https://github.com/downthemall/downthemall/releases) and [code.downthemall.org/releases](https://code.downthemall.org/releases/)

Now I hope all makes sense the way I phrased everything :)
