### ISSUE TITLE
Download Manga Image with custom attribute in html tag

### ISSUE THREAD

**Issue by apt42541** [downthemall/downthemall#443]
**Is your feature request related to a problem? Please describe.**
in old days , people use img src attribute then , it load fully on page refresh but now some go to use data-src lazy-loader for faster page loading

**Describe the solution you'd like**
DownThemAll should scrape link in data-src instead in network loaded tab 
**Describe alternatives you've considered**
still none.
**Additional context**
no.

**Comment by nmaier** [comment]
Yeah, this "work-around" some web developers came up with is a little bit annoying. Especially since about everybody seems to implement this differently.

I'll try to catch the common case, and look for a `data-src` element and check if it looks like a valid URL. Beyond that, it would require some kind of list describing a per-site way to handle this, which would not feasible for me to maintain I am afraid.
