### ISSUE TITLE
IP Adress Blocked from Website

### ISSUE THREAD

**Issue by dustin2551** [downthemall/downthemall#461]
**Desktop (please complete the following information):**
Windows 11 (Firefox Extension)

An owner of the website said he had to block my IP address because I kept crashing the website from using this Application. The programs stops downloading and the website crashes. He said it causes a memory error on his end. I've tried it on other smaller websites and it has been getting the same effect.

**Comment by nmaier** [comment]
I cannot speak to how website owners operate their websites. It's a little surprising to me, that DTA would case any trouble. The bit about "memory error on his end" indicates to me that the website in question is buggy and the solution was not actually fix the bug but kick you out instead. Not the option I'd have taken if it was my website. Aside, DownThemAll! downloads are just like any other browser downloads, except you can queue and download files quicker/in fewer clicks. If DownThemAll! causes his website issues, then "normal" browsers surely would as well, just maybe a little "slower".

I am closing this, because I cannot and do not want to dictate how website operators run their websites.
