### ISSUE TITLE
Odd things with pixiv

### ISSUE THREAD

**Issue by duvjones** [downthemall/downthemall#48]
**Desktop (please complete the following information):**
 - Windows 10 (version:1809)
 - Firefox 
 - Version: 68.0.2

**Describe the bug**
This is likely something to do with pixiv itself but for some reason every download through downthemall is not the image itself but some _168B_ blank file.

**To Reproduce**
1. Go to 'https://www.pixiv.net/member_illust.php?mode=medium&illust_id=76542723'
2. Click on the primary image to enlarge it
3.  Right click on the image and Scroll down to 'DownThemAll!' > 'Save image with DownThemAll!'
4. Click the 'download' button in the next popup
5. See error

**Expected behavior**
File is downloaded. Has a file size that is larger than _168B_.

**Additional context**

**Comment by nmaier** [comment]
This is due to #7 
Only Firefox 70+ allows us to set the referrer for a request, and some sites such as pixiv (just tested) check the referrer as a kind of hotlinking protection.

I cannot offer a solution other than either get Firefox Nightly now, or wait for the Firefox 70 stable release.
If there was something else I could do, I would, but Thank You WebExtensions for not letting me. Well, at least they fixed it only 2 years after I reported it, so that's something I guess...
