### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by ShelleyJ** [downthemall/downthemall#98]
### Your DownThemAll! and Browser Version and Language and Operating System
dTa: 3.0.6
Firefox: 48.0.2
Language: English
OpSys: Windows7

### Expected Behavior
I expect dTa to download embedded images from GMail messages. [It used to do this]

### Actual Behavior
For 99% of the embedded images, dTa returns an Error 403 status.

![clip](https://cloud.githubusercontent.com/assets/7309481/18653283/a1f25d6a-7e8d-11e6-90b3-6841bfe666dc.jpg)
![capture](https://cloud.githubusercontent.com/assets/7309481/18653284/a207817c-7e8d-11e6-8bac-36c962fdd16e.PNG)

### Steps To Reproduce
1. Select a bunch of images from a website on the "dTa Make Your Selection" screen.
2. Click "Start" 

### Additional info such as log extracts
If you need a Diagnostic Log, please contact me by email, and I will create one.

*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
The server says you are not authorized to request the data. Seeing this is google, it's probably google detecting you are requesting tons of stuff in a very limited time and then thinking you're some kind of bot (which technically is true, because DTA is an automated download "bot").

Since it is the server refusing connection, nothing we can do about it
